#[[imports]]
#name = "validate_int"
#file = "data/test_int_validator.xlsx"
#sheet = "test_int"
#schema = "dbo"
#table = "test_int"

#[[imports]]
#name = "report_data"
#file = "data/sample_report_data.xlsx"
#sheet = "ReportData"
#schema = "dbo"
#table = "ReportData"

#[[imports]]
#name = "validate_decimal"
#file = "data/test_decimal_validator.xlsx"
#sheet = "test_decimal"
#schema = "dbo"
#table = "test_decimal"

[[imports]]
name = "validate_datetime"
file = "data/test_datetime_validator.xlsx"
sheet = "test_datetime"
schema = "dbo"
table = "test_date"