# Copy this file to imports.toml and adjust values for your environment.

[[imports]]
name = "sales"
file = "data/sample_sales.xlsx"
sheet = "Sheet1"
schema = "dbo"
table = "Sales"
mode = "replace"

[[imports]]
name = "test_replace_columns"
file = "../data/test_replace_columns.xlsx"
sheet = "Sheet1"
schema = "dbo"
table = "test_replace_columns"
mode = "replace_by_columns"
replace_columns=["Name1", "Name2"]

[[imports]]
name = "products"
file = "data/products.xlsx"
sheet = "Products"
schema = "dbo"
table = "Products"
mode = "upsert"
key_columns = ["ID"]

[[imports]]
name = "product_stocks"
file = "data/test.xls"
sheet = "Sheet1"
schema = "dbo"
table = "ProductStocks"
mode = "append"

[imports.column_mapping]
"Столбец Excel 1" = "NewValue1"
"Столбец Excel 2" = "NewValue2"

[imports.date_formats]
ColumnNameDate = "%d.%m.%Y"
